package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ejercicio generated by hbm2java
 */
@Entity
@Table(name = "ejercicio")
public class Ejercicio implements java.io.Serializable {

    @Id
    @Column(name = "ID_EJERCICIO")
    private int idEjercicio;

    @JoinColumn(name = "ID_TIPO_EJERCICIO", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private TipoEjercicio tipoEjercicio;

    @Column(name = "nombre_ejercicio")
    private String nombreEjercicio;

    @Column(name = "dsc_ejercicio")
    private String dscEjercicio;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "ejercicio")
    private Set<Rutina> rutinas = new HashSet(0);
    
    @ManyToMany(cascade = {CascadeType.ALL}, mappedBy = "ejercicios")
    private Set<ParteCuerpo> parteCuerpos = new HashSet(0);

    public Ejercicio() {
    }

    public Ejercicio(int idEjercicio, TipoEjercicio tipoEjercicio, String nombreEjercicio, String dscEjercicio) {
        this.idEjercicio = idEjercicio;
        this.tipoEjercicio = tipoEjercicio;
        this.nombreEjercicio = nombreEjercicio;
        this.dscEjercicio = dscEjercicio;
    }

    public Ejercicio(int idEjercicio) {
        this.idEjercicio = idEjercicio;
    }

    public Ejercicio(int idEjercicio, TipoEjercicio tipoEjercicio, String nombreEjercicio, String dscEjercicio, Set rutinas, Set parteCuerpos) {
        this.idEjercicio = idEjercicio;
        this.tipoEjercicio = tipoEjercicio;
        this.nombreEjercicio = nombreEjercicio;
        this.dscEjercicio = dscEjercicio;
        this.rutinas = rutinas;
        this.parteCuerpos = parteCuerpos;
    }

    public int getIdEjercicio() {
        return this.idEjercicio;
    }

    public void setIdEjercicio(int idEjercicio) {
        this.idEjercicio = idEjercicio;
    }

    public TipoEjercicio getTipoEjercicio() {
        return this.tipoEjercicio;
    }

    public void setTipoEjercicio(TipoEjercicio tipoEjercicio) {
        this.tipoEjercicio = tipoEjercicio;
    }

    public String getNombreEjercicio() {
        return this.nombreEjercicio;
    }

    public void setNombreEjercicio(String nombreEjercicio) {
        this.nombreEjercicio = nombreEjercicio;
    }

    public String getDscEjercicio() {
        return this.dscEjercicio;
    }

    public void setDscEjercicio(String dscEjercicio) {
        this.dscEjercicio = dscEjercicio;
    }

    public Set getRutinas() {
        return this.rutinas;
    }

    public void setRutinas(Set rutinas) {
        this.rutinas = rutinas;
    }

    public Set getParteCuerpos() {
        return this.parteCuerpos;
    }

    public void setParteCuerpos(Set parteCuerpos) {
        this.parteCuerpos = parteCuerpos;
    }

    @Override
    public String toString() {
        return "Ejercicio{" + "idEjercicio=" + idEjercicio + ", nombreEjercicio=" + nombreEjercicio + ", dscEjercicio=" + dscEjercicio + '}';
    }

    
}
