package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Especialista generated by hbm2java
 */
public class Especialista  implements java.io.Serializable {


     private int idEspecialista;
     private String nombre;
     private Date fechaNacimiento;
     private String tarjetaProfesional;
     private Set grupoDeportivosForEspIdEspecialista = new HashSet(0);
     private Set rutinas = new HashSet(0);
     private Set grupoDeportivosForIdEspecialista = new HashSet(0);
     private Registro registro;

    public Especialista() {
    }

	
    public Especialista(int idEspecialista, String nombre, Date fechaNacimiento, String tarjetaProfesional) {
        this.idEspecialista = idEspecialista;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.tarjetaProfesional = tarjetaProfesional;
    }

    public Especialista(int idEspecialista, String nombre, Date fechaNacimiento, String tarjetaProfesional, Registro registro) {
        this.idEspecialista = idEspecialista;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
        this.tarjetaProfesional = tarjetaProfesional;
        this.registro = registro;
    }
    
    public Especialista(int idEspecialista, String nombre, Date fechaNacimiento, String tarjetaProfesional, Set grupoDeportivosForEspIdEspecialista, Set rutinas, Set grupoDeportivosForIdEspecialista, Registro registro) {
       this.idEspecialista = idEspecialista;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.tarjetaProfesional = tarjetaProfesional;
       this.grupoDeportivosForEspIdEspecialista = grupoDeportivosForEspIdEspecialista;
       this.rutinas = rutinas;
       this.grupoDeportivosForIdEspecialista = grupoDeportivosForIdEspecialista;
       this.registro = registro;
    }
   
    public int getIdEspecialista() {
        return this.idEspecialista;
    }
    
    public void setIdEspecialista(int idEspecialista) {
        this.idEspecialista = idEspecialista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getTarjetaProfesional() {
        return this.tarjetaProfesional;
    }
    
    public void setTarjetaProfesional(String tarjetaProfesional) {
        this.tarjetaProfesional = tarjetaProfesional;
    }
    public Set getGrupoDeportivosForEspIdEspecialista() {
        return this.grupoDeportivosForEspIdEspecialista;
    }
    
    public void setGrupoDeportivosForEspIdEspecialista(Set grupoDeportivosForEspIdEspecialista) {
        this.grupoDeportivosForEspIdEspecialista = grupoDeportivosForEspIdEspecialista;
    }
    public Set getRutinas() {
        return this.rutinas;
    }
    
    public void setRutinas(Set rutinas) {
        this.rutinas = rutinas;
    }
    public Set getGrupoDeportivosForIdEspecialista() {
        return this.grupoDeportivosForIdEspecialista;
    }
    
    public void setGrupoDeportivosForIdEspecialista(Set grupoDeportivosForIdEspecialista) {
        this.grupoDeportivosForIdEspecialista = grupoDeportivosForIdEspecialista;
    }
    public Registro getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Registro registro) {
        this.registro = registro;
    }

    @Override
    public String toString() {
        return "Especialista{" + "idEspecialista=" + idEspecialista + ", nombre=" + nombre + ", fechaNacimiento=" + fechaNacimiento + ", tarjetaProfesional=" + tarjetaProfesional + '}';
    }




}


