package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParteCuerpo generated by hbm2java
 */
@Entity
@Table(name = "parte_cuerpo")
public class ParteCuerpo implements java.io.Serializable {

    @Id
    @Column(name = "id_musculo")
    private int idMusculo;
    
    @JoinColumn(name = "PAR_ID_MUSCULO", nullable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private ParteCuerpo parteCuerpo;
    
    @Column(name = "dsc_musculo")
    private String dscMusculo;
    
    @ManyToMany(cascade = {CascadeType.ALL})
    @JoinTable(name = "musculo_ejercicio", joinColumns = {@JoinColumn(name = "id_musculo")}, inverseJoinColumns = {@JoinColumn(name = "id_ejercicio")})
    private Set<Ejercicio> ejercicios = new HashSet(0);
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "parteCuerpos")
    private Set<ParteCuerpo> parteCuerpos = new HashSet(0);

    public ParteCuerpo() {
    }

    public ParteCuerpo(int idMusculo, String dscMusculo) {
        this.idMusculo = idMusculo;
        this.dscMusculo = dscMusculo;
    }

    public ParteCuerpo(int idMusculo, ParteCuerpo parteCuerpo, String dscMusculo) {
        this.idMusculo = idMusculo;
        this.parteCuerpo = parteCuerpo;
        this.dscMusculo = dscMusculo;
    }
    

    public ParteCuerpo(int idMusculo, ParteCuerpo parteCuerpo, String dscMusculo, Set ejercicios, Set parteCuerpos) {
        this.idMusculo = idMusculo;
        this.parteCuerpo = parteCuerpo;
        this.dscMusculo = dscMusculo;
        this.ejercicios = ejercicios;
        this.parteCuerpos = parteCuerpos;
    }

    public int getIdMusculo() {
        return this.idMusculo;
    }

    public void setIdMusculo(int idMusculo) {
        this.idMusculo = idMusculo;
    }

    public ParteCuerpo getParteCuerpo() {
        return this.parteCuerpo;
    }

    public void setParteCuerpo(ParteCuerpo parteCuerpo) {
        this.parteCuerpo = parteCuerpo;
    }

    public String getDscMusculo() {
        return this.dscMusculo;
    }

    public void setDscMusculo(String dscMusculo) {
        this.dscMusculo = dscMusculo;
    }

    public Set getEjercicios() {
        return this.ejercicios;
    }

    public void setEjercicios(Set ejercicios) {
        this.ejercicios = ejercicios;
    }

    public Set getParteCuerpos() {
        return this.parteCuerpos;
    }

    public void setParteCuerpos(Set parteCuerpos) {
        this.parteCuerpos = parteCuerpos;
    }

    @Override
    public String toString() {
        return "ParteCuerpo{" + "idMusculo=" + idMusculo + ", dscMusculo=" + dscMusculo + '}';
    }

}
