package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "registro")
public class Registro implements java.io.Serializable {

    @Id
    @Column(name = "id_registro")
    private int idRegistro;

    @OneToOne
    @PrimaryKeyJoinColumn
    private Especialista especialista;

    @Column(name = "fecha_registro")
    private Date fechaRegistro;

    public Registro() {
    }

    public Registro(int idRegistro, Date fechaRegistro) {
        this.idRegistro = idRegistro;
        this.fechaRegistro = fechaRegistro;
    }

    public Registro(Especialista especialista) {
        this.especialista = especialista;
    }

    public Registro(Especialista especialista, Date fechaRegistro) {
        this.especialista = especialista;
        this.fechaRegistro = fechaRegistro;
    }

    public int getIdRegistro() {
        return this.idRegistro;
    }

    public void setIdRegistro(int idRegistro) {
        this.idRegistro = idRegistro;
    }

    public Especialista getEspecialista() {
        return this.especialista;
    }

    public void setEspecialista(Especialista especialista) {
        this.especialista = especialista;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    @Override
    public String toString() {
        return "Registro{" + "idRegistro=" + idRegistro + ", fechaRegistro=" + fechaRegistro + '}';
    }

}
