package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rutina generated by hbm2java
 */
@Entity
@Table(name = "rutina")
public class Rutina implements java.io.Serializable {

    @EmbeddedId
    private RutinaId id;

    @JoinColumn(name = "ID_EJERCICIO", nullable = false, insertable = false, updatable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Ejercicio ejercicio;

    @JoinColumn(name = "ID_ESPECIALISTA", nullable = false, insertable = false, updatable = false)
    @ManyToOne(optional = false, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Especialista especialista;

    @Column(name = "repeticiones")
    private short repeticiones;
    
    @Column(name = "duracion")
    private Date duracion;

    public Rutina() {
    }

    public Rutina(RutinaId id, Ejercicio ejercicio, Especialista especialista, short repeticiones, Date duracion) {
        this.id = id;
        this.ejercicio = ejercicio;
        this.especialista = especialista;
        this.repeticiones = repeticiones;
        this.duracion = duracion;
    }

    public Rutina(RutinaId id, Especialista especialista, short repeticiones, Date duracion) {
        this.id = id;
        this.especialista = especialista;
        this.repeticiones = repeticiones;
        this.duracion = duracion;
    }

    public RutinaId getId() {
        return this.id;
    }

    public void setId(RutinaId id) {
        this.id = id;
    }

    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }

    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }

    public Especialista getEspecialista() {
        return this.especialista;
    }

    public void setEspecialista(Especialista especialista) {
        this.especialista = especialista;
    }

    public short getRepeticiones() {
        return this.repeticiones;
    }

    public void setRepeticiones(short repeticiones) {
        this.repeticiones = repeticiones;
    }

    public Date getDuracion() {
        return this.duracion;
    }

    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }

    @Override
    public String toString() {
        return "Rutina{" + "id=" + id + ", ejercicio=" + ejercicio + ", repeticiones=" + repeticiones + ", duracion=" + duracion + '}';
    }

}
