package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RutinaId generated by hbm2java
 */
@Embeddable
public class RutinaId implements java.io.Serializable {

    @Column(name = "dia", nullable = false)
    private String dia;
    @Column(name = "id_ejercicio", nullable = false)
    private int idEjercicio;
    @Column(name = "id_especialista", nullable = false)
    private int idEspecialista;

    public RutinaId() {
    }

    public RutinaId(String dia, int idEjercicio, int idEspecialista) {
        this.dia = dia;
        this.idEjercicio = idEjercicio;
        this.idEspecialista = idEspecialista;
    }

    public String getDia() {
        return this.dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    public int getIdEjercicio() {
        return this.idEjercicio;
    }

    public void setIdEjercicio(int idEjercicio) {
        this.idEjercicio = idEjercicio;
    }

    public int getIdEspecialista() {
        return this.idEspecialista;
    }

    public void setIdEspecialista(int idEspecialista) {
        this.idEspecialista = idEspecialista;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RutinaId)) {
            return false;
        }
        RutinaId castOther = (RutinaId) other;

        return ((this.getDia() == castOther.getDia()) || (this.getDia() != null && castOther.getDia() != null && this.getDia().equals(castOther.getDia())))
                && (this.getIdEjercicio() == castOther.getIdEjercicio())
                && (this.getIdEspecialista() == castOther.getIdEspecialista());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDia() == null ? 0 : this.getDia().hashCode());
        result = 37 * result + this.getIdEjercicio();
        result = 37 * result + this.getIdEspecialista();
        return result;
    }

    @Override
    public String toString() {
        return "RutinaId{" + "dia=" + dia + ", idEjercicio=" + idEjercicio + ", idEspecialista=" + idEspecialista + '}';
    }

}
