package modelo;
// Generated 10/10/2020 11:26:52 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEjercicio generated by hbm2java
 */
@Entity
@Table(name = "tipo_ejercicio")
public class TipoEjercicio implements java.io.Serializable {

    @Id
    @Column(name = "id_tipo_ejercicio")
    private short idTipoEjercicio;

    @Column(name = "dsc_tipo_ejercicio")
    private String dscTipoEjercicio;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "tipoEjercicio")
    private Set<Ejercicio> ejercicios = new HashSet(0);

    public TipoEjercicio() {
    }

    public TipoEjercicio(short idTipoEjercicio, String dscTipoEjercicio) {
        this.idTipoEjercicio = idTipoEjercicio;
        this.dscTipoEjercicio = dscTipoEjercicio;
    }

    public TipoEjercicio(short idTipoEjercicio) {
        this.idTipoEjercicio = idTipoEjercicio;
    }

    public TipoEjercicio(short idTipoEjercicio, String dscTipoEjercicio, Set ejercicios) {
        this.idTipoEjercicio = idTipoEjercicio;
        this.dscTipoEjercicio = dscTipoEjercicio;
        this.ejercicios = ejercicios;
    }

    public short getIdTipoEjercicio() {
        return this.idTipoEjercicio;
    }

    public void setIdTipoEjercicio(short idTipoEjercicio) {
        this.idTipoEjercicio = idTipoEjercicio;
    }

    public String getDscTipoEjercicio() {
        return this.dscTipoEjercicio;
    }

    public void setDscTipoEjercicio(String dscTipoEjercicio) {
        this.dscTipoEjercicio = dscTipoEjercicio;
    }

    public Set getEjercicios() {
        return this.ejercicios;
    }

    public void setEjercicios(Set ejercicios) {
        this.ejercicios = ejercicios;
    }

    @Override
    public String toString() {
        return "TipoEjercicio{" + "idTipoEjercicio=" + idTipoEjercicio + ", dscTipoEjercicio=" + dscTipoEjercicio + '}';
    }

}
